apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
      # -> A porta exposta dentro do cluster, para por exemplo outro pod acessar
    - port: 5432 
      # -> Qualquer requisição que chegar na porta 4050 será redirecionada para a porta 4000 do container
      # -> Ela é igual a porta do containerPort dentro do arquivo de Pod ou deployment
      targetPort: 5432 

